'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8100';
const CAPABILITIES = ['authorized.network.discovery','authorized.web.assessment','authorized.vulnerability.assessment','evidence.collection'];
const LABELS = {'command-center':'Command Center','threat-intelligence':'Threat Intelligence','attack-surface':'Attack Surface','vulnerabilities':'Vulnerabilities','security-posture':'Security Posture','web-security':'Web & API Security','network-hardening':'Network & Hardening','compliance':'Compliance','ai-security':'Cyber AI','reports':'Reports'};

export default function OrganizationPage(){
 const [workspace,setWorkspace]=useState(null),[modules,setModules]=useState([]),[connector,setConnector]=useState({name:'CyberOS Kali Assessment Agent',environment:'on-premise',connector_type:'kali_agent',endpoint:'',capabilities:CAPABILITIES}),[message,setMessage]=useState('Loading tenant control plane…'),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [w,m]=await Promise.all([fetch(API+'/api/v1/organization').then(r=>r.json()),fetch(API+'/api/v1/modules').then(r=>r.json())]);setWorkspace(w);setModules(m);setMessage('Tenant workspace loaded · isolation enforced · execution policy active.')}catch(e){setMessage('Control plane unavailable — start Docker services and refresh.')}};
 useEffect(()=>{load()},[]);
 const enabledCount=useMemo(()=>modules.filter(m=>m.enabled).length,[modules]);
 const toggle=async(key,enabled)=>{setBusy(true);try{await fetch(API+'/api/v1/modules/'+key+'?enabled='+(!enabled),{method:'PATCH'});await load()}finally{setBusy(false)}};
 const register=async()=>{setBusy(true);setMessage('Registering customer-side assessment connector…');try{const r=await fetch(API+'/api/v1/connectors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(connector)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'registration failed');setMessage('Connector registered in '+d.status+' state. It cannot execute until approved and online.');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 return <main><aside><Brand/><nav><Link href="/command-center">Command Center</Link><Link className="active" href="/organization">Organization</Link><Link href="/operations">Operations</Link>{Object.entries(LABELS).filter(([k])=>k!=='command-center').map(([k,n])=><Link key={k} href={'/module/'+k}>{n}</Link>)}</nav><div className="tenant"><small>ACTIVE TENANT</small><strong>{workspace?.tenant?.name||'Loading…'}</strong><span>● TENANT-SCOPED CONTROL</span></div></aside>
 <section className="content"><header><div><span className="eyebrow">TENANT CONTROL PLANE / SECURITY WORKSPACE</span><h1>Organization</h1><p>This is the customer administration boundary: identity, modules, assets, connectors, authorization and assessment scope. The public website remains unchanged; this is the application workspace behind customer login.</p></div><Link className="primary" href="/operations">Open Operations →</Link></header>
 <div className="status"><span className="dot"/>{message}<span className="sep">|</span>Tenant isolation: <b>ENFORCED</b><span className="sep">|</span>Network execution: <b>AGENT + AUTHORIZATION</b></div>
 <div className="metrics"><Metric value={workspace?.tenant?.name||'—'} label="Tenant" sub={workspace?.tenant?.industry||'Organization profile'}/><Metric value={enabledCount} label="Enabled modules" sub="Per-tenant entitlement"/><Metric value={workspace?.assets?.length??'—'} label="Mapped assets" sub="Tenant asset inventory"/><Metric value={workspace?.connectors?.length??'—'} label="Connectors" sub="Customer-side integrations"/></div>
 <section className="panel"><Head eyebrow="1 / CUSTOMER IDENTITY" title="Who is entering this workspace?" pill="TENANT BOUNDARY"/><div className="form-grid"><Field label="Organization" value={workspace?.tenant?.name||''}/><Field label="Industry" value={workspace?.tenant?.industry||''}/><Field label="Region" value={workspace?.tenant?.region||''}/><Field label="Current role" value={workspace?.identity?.role||''}/></div><div className="security-strip"><b>Authorization context</b><span>{workspace?.authorization?.id||'—'}</span><span>Mode: {workspace?.authorization?.mode||'—'}</span><span>Status: {workspace?.authorization?.status||'—'}</span></div></section>
 <section className="panel"><Head eyebrow="2 / SECURITY MODULES" title="Select what this organization operates" pill={enabledCount+' ENABLED'}/><div className="grid">{modules.map(m=><button disabled={busy} key={m.key} className={'module-card '+(m.enabled?'selected':'')} onClick={()=>toggle(m.key,m.enabled)}><span className="num">{LABELS[m.key]?.slice(0,2).toUpperCase()}</span><h3>{LABELS[m.key]||m.key}</h3><p>{description(m.key)}</p><span className="arrow">{m.enabled?'✓ Enabled for tenant':'Enable module →'}</span></button>)}</div></section>
 <section className="lower"><div className="panel"><Head eyebrow="3 / ENVIRONMENT CONNECTORS" title="Connect cloud, data center or hybrid infrastructure" pill="OUTBOUND MODEL"/><p>CyberOS should not require an unrestricted inbound path into a customer network. A customer-controlled connector/agent establishes the controlled execution boundary and returns inventory, telemetry and evidence.</p><div className="connector-list">{(workspace?.connectors||[]).map(c=><div key={c.id}><b>{c.name}</b><span>{c.type} · {c.environment} · {c.status}</span><small>{(c.capabilities||[]).join(' · ')||'No execution capabilities configured'}</small></div>)}{!(workspace?.connectors||[]).length&&<div><b>No customer connector registered</b><span>Register the Kali/customer assessment agent below.</span></div>}</div></div>
 <div className="panel"><Head eyebrow="4 / KALI / ASSESSMENT AGENT" title="Customer-side security execution" pill="AUTHORIZATION GATED"/><div className="form-grid one"><Field label="Agent name" value={connector.name} onChange={e=>setConnector({...connector,name:e.target.value})}/><Field label="Agent endpoint / ID" value={connector.endpoint} onChange={e=>setConnector({...connector,endpoint:e.target.value})}/></div><div className="capabilities">{CAPABILITIES.map(c=><span key={c}>{c}</span>)}</div><button className="primary action" disabled={busy} onClick={register}>{busy?'Working…':'Register customer assessment agent →'}</button><small className="note">Registration does not start a scan. Active network assessment requires an approved engagement, explicit target scope/exclusions, an online customer connector and an authorized job.</small></div></section>
 <section className="panel"><Head eyebrow="5 / ASSET MAPPING" title="What CyberOS will build after connection" pill="CONTINUOUS INVENTORY"/><div className="asset-map">{(workspace?.assets||[]).map(a=><div key={a.id}><div><strong>{a.name}</strong><span>{a.type} · {a.environment}</span></div><b>{a.exposure}</b><small>{a.identifier}</small></div>)}{!(workspace?.assets||[]).length&&<div className="empty">No assets mapped yet. The first connector discovery job will populate this tenant inventory.</div>}</div></section>
 <footer>CYBEROS M2.2 · Tenant onboarding / module entitlements / asset mapping / customer-agent gateway · Public website layout unchanged</footer></section></main>
}
function Brand(){return <div className="brand"><span className="mark">C</span><div><b>CYBEROS</b><small>GLOBAL SECURITY PLATFORM</small></div></div>}
function Head({eyebrow,title,pill}){return <div className="panelhead"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><span className="pill">{pill}</span></div>}
function Metric({value,label,sub}){return <div className="metric"><strong>{value}</strong><span>{label}</span><small>{sub}</small></div>}
function Field({label,value,onChange}){return <label className="field"><span>{label}</span><input value={value} onChange={onChange} readOnly={!onChange}/></label>}
function description(k){return {'command-center':'Executive and operational security picture','threat-intelligence':'Global intelligence correlated to this tenant','attack-surface':'Internet-facing exposure and attack paths','vulnerabilities':'CVE / KEV / exploitability prioritization','security-posture':'Cloud, data-center and hybrid posture','web-security':'Authorized application and API assessment','network-hardening':'Architecture, segmentation and hardening','compliance':'ISO · PCI DSS · DORA · SOC 2 · NIST','ai-security':'Evidence-grounded security analysis','reports':'Executive, technical and assurance reporting'}[k]||'Tenant security capability'}
