'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

const css = `
.ti-page{min-height:100vh;background:#071016;color:#dce8ed;font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;padding:28px 32px}.ti-shell{max-width:1500px;margin:auto}.ti-top{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;border-bottom:1px solid #193039;padding-bottom:22px}.ti-brand{display:flex;gap:12px;align-items:center}.ti-mark{width:38px;height:38px;border:2px solid #55d6c2;border-radius:10px;display:grid;place-items:center;color:#55d6c2;font-weight:800}.ti-brand b{display:block;letter-spacing:2px}.ti-brand small{color:#607e86;font-size:8px;letter-spacing:1px}.ti-top h1{margin:18px 0 6px;font-size:32px}.ti-top p{margin:0;color:#78939b;max-width:760px;line-height:1.7}.ti-actions{display:flex;gap:10px;flex-wrap:wrap}.ti-btn{border:1px solid #29434a;border-radius:8px;padding:10px 14px;color:#9ab1b8;font-size:12px}.ti-btn.primary{background:#62dfca;color:#071016;border-color:#62dfca;font-weight:700}.ti-status{margin:18px 0;padding:11px 14px;border:1px solid #1b3a42;background:#09171d;border-radius:8px;color:#73919a;font-size:11px}.ti-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.ti-card{border:1px solid #19323a;background:#09171d;border-radius:10px;padding:20px}.ti-card h2{font-size:16px;margin:0 0 6px}.ti-sub{color:#68858d;font-size:11px;margin-bottom:18px}.ti-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.ti-metric{border:1px solid #17323a;background:#0b1b21;border-radius:8px;padding:14px}.ti-metric span{display:block;color:#5e7d85;font-size:9px;text-transform:uppercase}.ti-metric strong{display:block;font-size:23px;margin-top:7px}.ti-table{display:grid;gap:8px}.ti-row{display:grid;grid-template-columns:1.2fr 90px 90px 1.4fr;gap:12px;align-items:center;border:1px solid #152d35;background:#0b1b21;border-radius:7px;padding:12px;font-size:11px}.ti-row small{display:block;color:#5f7c84;margin-top:3px}.ti-score{font-weight:800}.critical{color:#ff8f8f}.high{color:#f2c36b}.medium{color:#75cfc0}.monitor{color:#78939b}.ti-reasons{margin:8px 0 0;padding-left:18px;color:#718b93;font-size:10px;line-height:1.7}.ti-profile{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ti-profile div{border:1px solid #17323a;background:#0b1b21;border-radius:7px;padding:12px}.ti-profile span{display:block;color:#5e7d85;font-size:9px;text-transform:uppercase}.ti-profile b{display:block;margin-top:5px;font-size:12px}.ti-wide{margin-top:16px}.ti-note{color:#5f7c84;font-size:10px;line-height:1.6;margin-top:14px}@media(max-width:1000px){.ti-grid{grid-template-columns:1fr}.ti-metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.ti-page{padding:18px}.ti-top{display:block}.ti-actions{margin-top:16px}.ti-row{grid-template-columns:1fr 70px}.ti-row>span:nth-child(3),.ti-row>div:nth-child(4){grid-column:1/-1}.ti-profile{grid-template-columns:1fr}}
`;

export default function TenantThreatIntelligence(){
 const [data,setData]=useState(null); const [profile,setProfile]=useState(null); const [error,setError]=useState('Loading tenant intelligence…');
 const base=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8100';
 useEffect(()=>{Promise.all([fetch(base+'/api/v1/threat-intelligence/correlations').then(r=>r.json()),fetch(base+'/api/v1/threat-intelligence/profile').then(r=>r.json())]).then(([c,p])=>{setData(c);setProfile(p);setError('Live · Tenant-scoped correlation engine')}).catch(()=>setError('Threat intelligence service unavailable'))},[base]);
 const correlations=data?.correlations||[];
 return <main className="ti-page"><style>{css}</style><div className="ti-shell">
  <header className="ti-top"><div><div className="ti-brand"><span className="ti-mark">C</span><div><b>CYBEROS</b><small>TENANT THREAT INTELLIGENCE</small></div></div><h1>Tenant-Relevant Threat Intelligence</h1><p>Global intelligence is continuously evaluated against this organization's sector, geography, technology footprint, exposure, vulnerabilities and assets. Global knowledge is reusable; tenant-derived correlations stay tenant-scoped.</p></div><div className="ti-actions"><Link className="ti-btn" href="/command-center">← Command Center</Link><Link className="ti-btn" href="/module/threat-intelligence">Threat Intelligence</Link></div></header>
  <div className="ti-status">● {error} <span style={{marginLeft:14}}>Isolation: <b>ACTIVE</b></span> <span style={{marginLeft:14}}>Execution: <b>POLICY CONTROLLED</b></span></div>
  {profile&&<><div className="ti-metrics"><div className="ti-metric"><span>Tenant</span><strong>{profile.tenant.name}</strong></div><div className="ti-metric"><span>Assets</span><strong>{profile.asset_count}</strong></div><div className="ti-metric"><span>Open findings</span><strong>{profile.open_finding_count}</strong></div><div className="ti-metric"><span>Technologies</span><strong>{profile.technologies.length}</strong></div></div><section className="ti-card ti-wide"><h2>Tenant Intelligence Profile</h2><div className="ti-sub">Context used by the correlation engine — no cross-tenant data.</div><div className="ti-profile"><div><span>Organization</span><b>{profile.tenant.name}</b></div><div><span>Industry</span><b>{profile.tenant.industry||'Not configured'}</b></div><div><span>Region</span><b>{profile.tenant.region||'Not configured'}</b></div><div><span>Tier</span><b>{profile.tenant.subscription_tier}</b></div><div><span>Technology footprint</span><b>{profile.technologies.join(' · ')||'None detected'}</b></div><div><span>Exposure</span><b>{profile.exposures.join(' · ')||'None recorded'}</b></div></div></section></>}
  <div className="ti-grid ti-wide"><section className="ti-card"><h2>Tenant Correlation Queue</h2><div className="ti-sub">Global intelligence ranked by relevance to this tenant.</div><div className="ti-table">{correlations.map(c=><article className="ti-row" key={c.intelligence_id}><div><b>{c.title}</b><small>{c.intelligence_id} · {c.type}</small></div><span className={'ti-score '+c.priority}>{c.priority.toUpperCase()}</span><span>{c.relevance_score}/100</span><div><b>Why it matters</b><ul className="ti-reasons">{c.reasons.slice(0,3).map(r=><li key={r}>{r}</li>)}</ul></div></article>)}</div></section><section className="ti-card"><h2>Correlation Model</h2><div className="ti-sub">The decision path used for every tenant-relevant signal.</div><div className="ti-profile"><div><span>01</span><b>Global intelligence</b></div><div><span>02</span><b>Tenant context</b></div><div><span>03</span><b>Asset / finding match</b></div><div><span>04</span><b>Relevance score</b></div><div><span>05</span><b>Confidence + evidence</b></div><div><span>06</span><b>Module propagation</b></div></div><p className="ti-note">Future ingestion will use normalized STIX/TAXII-compatible intelligence and ATT&amp;CK relationships. Correlations will feed Command Center, Vulnerability, Attack Surface, Posture, Web/API Security, Network, Compliance, AI and Reports.</p></section></div>
 </div></main>;
}
