'use client';
import Link from 'next/link';
import { useState } from 'react';

const modules=[['Threat Intelligence','threat-intelligence'],['Attack Surface','attack-surface'],['Vulnerability Intelligence','vulnerabilities'],['Security Posture','security-posture'],['Web & API Security','web-security'],['Network & Hardening','network-hardening'],['Compliance / GRC','compliance'],['Cyber AI','ai-security'],['Reports','reports']];
const environments=['Cloud — AWS / Azure / GCP','On-premise data center','Hybrid environment','Web applications / APIs','Network devices','Servers / endpoints','Kubernetes / containers'];
export default function OnboardingPage(){
 const [selected,setSelected]=useState(['Threat Intelligence','Security Posture','Reports']);
 const toggle=(m)=>setSelected(x=>x.includes(m)?x.filter(v=>v!==m):[...x,m]);
 return <main className="module-page"><aside><div className="brand"><span className="mark">C</span><div><b>CYBEROS</b><small>GLOBAL SECURITY PLATFORM</small></div></div><nav><Link href="/command-center">Command Center</Link><Link className="active" href="/organization">Organization</Link><Link href="/operations">Operations</Link>{modules.map(([label,slug])=><Link key={slug} href={'/module/'+slug}>{label}</Link>)}</nav><div className="tenant"><small>ONBOARDING</small><strong>New customer tenant</strong><span>● SETUP WORKFLOW</span></div></aside>
 <section className="content"><header><div><span className="eyebrow">CUSTOMER ONBOARDING / TENANT SETUP</span><h1>Configure your security program</h1><p>Set the organizational context first. Connectivity and security testing are separate, explicitly authorized stages.</p></div><Link className="primary" href="/command-center">Command Center →</Link></header>
 <div className="status"><span className="dot"></span>Step 1 of 4 · Organization → Modules → Connectivity → Authorized assessment</div>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">01 / ORGANIZATION</span><h2>Organization profile</h2></div><span className="pill">TENANT CREATION</span></div><div className="context-grid"><Field label="Organization" value="Your organization"/><Field label="Industry" value="Financial Services"/><Field label="Operating region" value="India / APAC"/><Field label="Risk profile" value="Enterprise / regulated"/></div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">02 / ENTITLEMENTS</span><h2>Select security capabilities</h2></div><span className="pill">{selected.length} SELECTED</span></div><div className="grid">{modules.map(([m])=><button key={m} className={'module-card '+(selected.includes(m)?'selected':'')} onClick={()=>toggle(m)}><span className="num">{selected.includes(m)?'✓':'+'}</span><h3>{m}</h3><p>{selected.includes(m)?'Enabled for this tenant configuration.':'Available when included by plan / entitlement.'}</p></button>)}</div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">03 / CONNECTIVITY</span><h2>Choose environments to onboard</h2></div><span className="pill">NO SCAN STARTED</span></div><div className="grid">{environments.map((e,i)=><div className="module-card" key={e}><span className="num">0{i+1}</span><h3>{e}</h3><p>Enroll a least-privilege connector or integration. Connectivity alone never authorizes scanning.</p><span className="arrow">Configure later →</span></div>)}</div></section>
 <section className="lower"><div className="panel architecture"><span className="eyebrow">04 / AUTHORIZED ASSESSMENT</span><h2>Nothing runs automatically</h2><p>After connectivity, an authorized operator defines targets, exclusions, time windows and assessment type. CyberOS validates tenant, role, entitlement, scope and tool policy before a worker can execute.</p><div className="flow"><span><b>Scope</b><i>→</i></span><span><b>Authorize</b><i>→</i></span><span><b>Validate policy</b><i>→</i></span><span><b>Execute</b><i>→</i></span><span><b>Evidence</b></span></div><button className="primary action" onClick={()=>alert('M2 onboarding shell saved. Backend tenant persistence and connector enrollment are next platform-kernel steps.')}>Save tenant configuration →</button></div><div className="panel score"><span className="eyebrow">SECURITY BOUNDARY</span><div className="ring">ON</div><h2>Tenant isolated</h2><p>Customer data, jobs, findings and evidence will remain scoped to this tenant.</p></div></section>
 </section></main>
}
function Field({label,value}){return <div className="context-card"><span>{label}</span><strong style={{fontSize:14}}>{value}</strong><small>Editable in organization settings</small></div>}
