'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

export default function OperationsPage(){
 const base=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8100';
 const [jobs,setJobs]=useState([]),[audit,setAudit]=useState([]),[health,setHealth]=useState('Checking control plane…'),[message,setMessage]=useState('');
 const load=async()=>{try{const [j,a,h]=await Promise.all([fetch(base+'/api/v1/demo/jobs').then(r=>r.json()),fetch(base+'/api/v1/audit').then(r=>r.json()),fetch(base+'/health').then(r=>r.json())]);setJobs(j);setAudit(a);setHealth('Control plane '+h.status+' · Database '+h.database)}catch{setHealth('Control plane unavailable')}};
 useEffect(()=>{load()},[]);
 const preview=async()=>{setMessage('Policy preview requested…');try{const r=await fetch(base+'/api/v1/jobs/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capability:'demo.asset_inventory',target:'demo-edge-fw',authorized:true})});const d=await r.json();setMessage(d.status==='policy_review_required'?'Policy gate passed preview: explicit authorization and approval remain required.':'Blocked → '+d.reason);await load()}catch{setMessage('Control plane unavailable')}};
 return <main><aside><div className="brand"><span className="mark">C</span><div><b>CYBEROS</b><small>GLOBAL SECURITY PLATFORM</small></div></div><nav><Link href="/command-center">Command Center</Link><Link href="/organization">Organization</Link><Link className="active" href="/operations">Operations</Link><Link href="/module/threat-intelligence">Threat Intelligence</Link><Link href="/module/attack-surface">Attack Surface</Link><Link href="/module/vulnerabilities">Vulnerabilities</Link><Link href="/module/security-posture">Security Posture</Link><Link href="/module/web-security">Web Security</Link><Link href="/module/network-hardening">Network &amp; Hardening</Link><Link href="/module/compliance">Compliance</Link><Link href="/module/ai-security">Cyber AI</Link><Link href="/module/reports">Reports</Link></nav><div className="tenant"><small>ACTIVE TENANT</small><strong>CyberOS Global</strong><span>● M2 PRODUCT EXPERIENCE</span></div></aside>
 <section className="content"><header><div><span className="eyebrow">TENANT CONTROL PLANE / OPERATIONS</span><h1>Operations</h1><p>Central execution gateway for authorized assessments, connector jobs, evidence collection, remediation workflows and audit events.</p></div><Link className="primary" href="/organization">Organization setup →</Link></header>
 <div className="status"><span className="dot"/>{health}<span className="sep">|</span>Execution policy: <b>ENFORCED</b><span className="sep">|</span>Tenant: <b>CyberOS Global</b></div>
 <div className="metrics"><div className="metric"><strong>{jobs.filter(j=>j.state==='running').length}</strong><span>Running jobs</span><small>Tenant-scoped execution</small></div><div className="metric"><strong>{jobs.filter(j=>j.state==='queued').length}</strong><span>Queued jobs</span><small>Waiting for worker</small></div><div className="metric"><strong>{jobs.filter(j=>j.state==='blocked').length}</strong><span>Blocked requests</span><small>Policy denied</small></div><div className="metric"><strong>{audit.length}</strong><span>Recent audit events</span><small>Evidence ledger</small></div></div>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">CONTROLLED EXECUTION</span><h2>Security execution lifecycle</h2></div><span className="pill">POLICY GATED</span></div><div className="flow"><b>Request</b><i>→</i><b>Scope</b><i>→</i><b>Authorize</b><i>→</i><b>Execute</b><i>→</i><b>Evidence</b><i>→</i><b>Report</b></div><p>Every active security action must carry tenant context, an authorized identity, an allowed capability and an approved target scope. Production connectors will execute from controlled customer-side agents.</p><button className="primary action" onClick={preview}>Run safe policy preview →</button>{message&&<div className="status">{message}</div>}</section>
 <section className="lower"><div className="panel"><div className="panelhead"><div><span className="eyebrow">JOB QUEUE</span><h2>Recent execution requests</h2></div><span className="pill">LIVE</span></div><div className="table">{jobs.length?jobs.slice(0,8).map(j=><div className="row" key={j.id}><div><strong>{j.capability}</strong><small>{j.target}</small></div><span className="severity">{j.state}</span><span>{new Date(j.created_at).toLocaleTimeString()}</span></div>):<div className="empty">No execution requests recorded yet.</div>}</div></div><div className="panel"><div className="panelhead"><div><span className="eyebrow">AUDIT LEDGER</span><h2>Recent events</h2></div><span className="pill">TRACEABLE</span></div><div className="table">{audit.length?audit.slice(0,8).map(e=><div className="row compact" key={e.id}><div><strong>{e.event_type}</strong><small>{e.actor||'system'} · {e.resource_type}</small></div><span className="severity">{e.decision}</span><span>{new Date(e.created_at).toLocaleTimeString()}</span></div>):<div className="empty">No operational events recorded yet.</div>}</div></div></section>
 <section className="panel"><span className="eyebrow">EXECUTION SAFETY</span><h2>Customer network protection model</h2><div className="flow"><b>CyberOS control plane</b><i>→</i><b>Policy gateway</b><i>→</i><b>Customer connector</b><i>→</i><b>Scoped target</b></div><p>For on-premise and hybrid environments, the preferred architecture is an outbound-controlled connector/agent. It receives only approved jobs, executes within the authorized scope, returns evidence and records the full audit trail.</p></section>
 <footer>CYBEROS M2 · Operations / Authorization / Execution / Audit · Demo execution is synthetic-only</footer></section></main>
}
