'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';

const modules = [
  ['Threat Intelligence','threat-intelligence'], ['Attack Surface','attack-surface'], ['Vulnerabilities','vulnerabilities'],
  ['Security Posture','security-posture'], ['Web Security','web-security'], ['Network & Hardening','network-hardening'],
  ['Compliance','compliance'], ['AI Security','ai-security'], ['Reports','reports'],
];

const catalog = {
  'threat-intelligence': { name:'Threat Intelligence', eyebrow:'GLOBAL THREAT INTELLIGENCE', description:'Correlate actors, campaigns, malware, IOCs, vulnerabilities and geopolitical signals into a global threat picture.', stats:[['84','Active campaigns'],['312','Threat actors'],['1,842','IOCs correlated'],['27','High-risk regions']], title:'Global Threat Pulse', subtitle:'Threat activity by region, campaign and asset relevance', rows:[['APT activity','Eastern Europe / Energy','HIGH','Actor + campaign correlated'],['Ransomware','Global / Manufacturing','HIGH','18 indicators linked'],['Cloud credential abuse','North America / SaaS','MEDIUM','Identity telemetry'],['Exploit campaign','APAC / Internet edge','HIGH','KEV + exposure overlap']], flow:['Ingest feeds','Normalize STIX/TAXII','Correlate','Score','Alert / brief'] },
  'attack-surface': { name:'Attack Surface', eyebrow:'EXTERNAL ATTACK SURFACE', description:'Maintain a continuously changing inventory of domains, IPs, applications, APIs, certificates and exposed services across cloud, on-premise and hybrid estates.', stats:[['428','Internet assets'],['96','Applications'],['214','APIs / endpoints'],['31','Critical exposures']], title:'Exposure Command View', subtitle:'External exposure, business context and change over time', rows:[['api.customer.example','API','CRITICAL','Authentication gap'],['vpn-edge-02','Remote access','HIGH','Legacy TLS'],['portal.example','Web application','MEDIUM','Missing security headers'],['cloud-gw-17','Cloud gateway','HIGH','Public management port']], flow:['Discover','Fingerprint','Classify','Prioritize','Remediate'] },
  'vulnerabilities': { name:'Vulnerabilities', eyebrow:'VULNERABILITY INTELLIGENCE', description:'Turn CVE, CWE, CVSS, KEV, vendor advisories and asset context into risk-prioritized remediation decisions.', stats:[['1,284','Open vulnerabilities'],['42','Critical'],['118','KEV-linked'],['76%','Remediated < 30d']], title:'Risk & Remediation', subtitle:'Exploitability, exposure and remediation pressure', rows:[['CVE-2026-XXXX','Internet-facing gateway','CRITICAL','KEV / exposed'],['CVE-2026-YYYY','Identity service','HIGH','Privilege boundary'],['CVE-2026-ZZZZ','Customer API','HIGH','Application impact'],['CVE-2026-AAAA','Build runner','MEDIUM','Supply-chain context']], flow:['Ingest CVEs','Correlate assets','Score risk','Assign owner','Verify fix'] },
  'security-posture': { name:'Security Posture', eyebrow:'UNIFIED SECURITY POSTURE', description:'Measure security posture across cloud, on-premise data centers, endpoints, servers and hybrid infrastructure against policy and security baselines.', stats:[['82','Posture score'],['91%','Cloud coverage'],['76%','DC coverage'],['68%','Hybrid controls']], title:'Infrastructure Security Posture', subtitle:'Cloud · On-premise DC · Hybrid · Endpoint control coverage', rows:[['Cloud','AWS / Azure / GCP','82%','CSPM controls'],['Data center','Servers / network','76%','CIS hardening'],['Hybrid','Identity / connectivity','68%','Segmentation'],['Endpoint','Workstations / EDR','79%','EDR telemetry']], flow:['Inventory','Assess','Compare baseline','Prioritize','Improve'] },
  'web-security': { name:'Web Security', eyebrow:'APPLICATION & API SECURITY', description:'Assess authorized web applications and APIs for injection, access control, authentication, configuration, secrets, supply-chain and runtime security weaknesses.', stats:[['96','Web apps'],['214','API surfaces'],['17','SQLi candidates'],['11','Critical findings']], title:'Application Security Center', subtitle:'Authorized SAST / DAST / IAST / API assessment with evidence', rows:[['Customer Portal','SQL Injection','CRITICAL','DAST candidate'],['Payments API','Broken access control','HIGH','Authorization test'],['Admin Console','XSS','HIGH','Input validation'],['Mobile API','Weak authentication','HIGH','Token policy']], flow:['Map app','Discover inputs','Test safely','Correlate code + runtime','Evidence / retest'] },
  'network-hardening': { name:'Network & Hardening', eyebrow:'SECURE NETWORK ARCHITECTURE', description:'Design and assess secure network architecture across firewalls, routers, switches, servers, segmentation, remote access and hybrid connectivity.', stats:[['47','Network devices'],['18','Security zones'],['89%','Firewall baseline'],['73%','Segmentation score']], title:'Network Architecture & Hardening', subtitle:'Topology, segmentation and configuration assurance', rows:[['Internet edge','Firewall cluster','89%','Policy baseline'],['Core network','Routers / switches','81%','Secure config'],['Server zones','East / west flows','73%','Segmentation gap'],['Remote access','VPN / ZTNA','76%','Identity controls']], flow:['Discover topology','Model trust zones','Assess controls','Harden','Verify'] },
  'compliance': { name:'Compliance', eyebrow:'GRC & ASSURANCE', description:'Map frameworks to controls, assets, evidence, findings, risk, remediation and verification instead of treating compliance as a static checklist.', stats:[['5','Frameworks'],['184','Controls'],['76%','Evidence coverage'],['23','Open gaps']], title:'Assurance Control Center', subtitle:'ISO 27001 · PCI DSS · DORA · SOC 2 · NIST CSF', rows:[['Access Control','ISO 27001 A.5','Mapped','Evidence linked'],['Logging','PCI DSS 10','Partial','Gap remediation'],['Risk management','DORA','Mapped','Owner assigned'],['Security monitoring','NIST CSF','Partial','Telemetry pending']], flow:['Framework','Controls','Assets','Evidence','Finding → remediation'] },
  'ai-security': { name:'AI Security', eyebrow:'CYBER AI ANALYST', description:'Use evidence-grounded AI to correlate security context, explain risk, support analysts and generate auditable recommendations without bypassing policy controls.', stats:[['9','AI workstreams'],['312','Correlations'],['94%','Evidence grounded'],['0','Unapproved executions']], title:'AI Security Operations', subtitle:'Analyst assistance, correlation, prediction and guarded actions', rows:[['Threat analyst','Campaign correlation','Ready','Evidence linked'],['Vulnerability analyst','Risk explanation','Ready','Asset context'],['Security architect','Control recommendation','Review','Human approval'],['Report generator','Executive brief','Ready','Source traceable']], flow:['Observe','Correlate','Explain','Recommend','Human approval'] },
  'reports': { name:'Reports', eyebrow:'SECURITY REPORTING & EVIDENCE', description:'Generate executive, technical, compliance, remediation and assessment reports from one evidence-backed security record.', stats:[['38','Report templates'],['12','Scheduled reports'],['94%','Evidence linked'],['7','Executive packs']], title:'Reporting Command View', subtitle:'Executive posture, technical findings, compliance evidence and remediation', rows:[['Executive risk brief','Leadership','Weekly','Ready'],['Vulnerability report','Security team','Daily','Ready'],['PCI DSS evidence pack','Audit','On demand','Ready'],['Pentest / assessment','Technical','Engagement','Evidence linked']], flow:['Collect evidence','Normalize','Compose','Review','Publish'] },
};

export default function ModulePage() {
  const { slug } = useParams();
  const cfg = catalog[slug] || catalog['security-posture'];
  const [summary,setSummary]=useState(null), [assets,setAssets]=useState([]), [findings,setFindings]=useState([]), [jobs,setJobs]=useState([]);
  const [message,setMessage]=useState('Loading live control-plane data…'), [jobState,setJobState]=useState(''), [running,setRunning]=useState(false);
  const base=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8100';
  useEffect(()=>{ Promise.all([
    fetch(base+'/api/v1/demo/summary').then(r=>r.json()), fetch(base+'/api/v1/demo/assets').then(r=>r.json()),
    fetch(base+'/api/v1/demo/findings').then(r=>r.json()), fetch(base+'/api/v1/demo/jobs').then(r=>r.json())
  ]).then(([s,a,f,j])=>{setSummary(s);setAssets(a);setFindings(f);setJobs(j);setMessage('Live · Demo tenant · Policy engine enforced');}).catch(()=>setMessage('Control plane unavailable')); },[base]);
  const launch=async()=>{setRunning(true);setJobState('Submitting through authorization and policy checks…');try{const r=await fetch(base+'/api/v1/demo/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capability:'demo.asset_inventory',target:'demo-edge-fw',authorized:true})});const d=await r.json();setJobState(d.state==='queued'?'Authorized → queued → worker execution':'Blocked → '+(d.policy_reason||'policy denied'));}catch{setJobState('Control plane unavailable')}finally{setRunning(false)}};
  const live=useMemo(()=>({assets:summary?.assets??cfg.stats[0][0],findings:summary?.open_findings??cfg.stats[1][0],jobs:summary?.jobs??'0',frameworks:summary?.frameworks??'5'}),[summary,cfg]);
  return <main className="module-page">
    <aside><div className="brand"><span className="mark">C</span><div><b>CYBEROS</b><small>GLOBAL SECURITY PLATFORM</small></div></div><nav>
      <Link href="/command-center">Command Center</Link><Link href="/organization">Organization</Link><Link href="/operations">Operations</Link>
      {modules.map(([label,key])=><Link key={key} className={key===slug?'active':''} href={'/module/'+key}>{label}</Link>)}
    </nav><div className="tenant"><small>DEMO TENANT</small><strong>CyberOS Global</strong><span>● M2 PRODUCT EXPERIENCE</span></div></aside>
    <section className="content"><header><div><span className="eyebrow">{cfg.eyebrow}</span><h1>{cfg.name}</h1><p>{cfg.description}</p></div><Link className="primary" href="/command-center">← Command Center</Link></header>
      <div className="status"><span className="dot"></span>{message}<span className="sep">|</span>Tenant isolation: <b>ACTIVE</b><span className="sep">|</span>Execution: <b>POLICY CONTROLLED</b></div>
      <div className="metrics">{cfg.stats.map(([n,l],i)=><Metric key={l} n={i===0&&slug==='vulnerabilities'?live.findings:n} l={l} s={i===0?'Current module view':'Demo analytics'}/>)}</div>
      <section className="panel"><div className="panelhead"><div><span className="eyebrow">{cfg.name.toUpperCase()} ANALYTICS</span><h2>{cfg.title}</h2><p className="panel-subtitle">{cfg.subtitle}</p></div><span className="pill">TENANT-SCOPED</span></div>
        <div className="analytics-grid"><div className="chart-card"><h3>Risk / activity trend</h3><div className="bars">{[42,58,51,67,74,61,82,76,88,72,91,84].map((v,i)=><span key={i} style={{height:v+'%'}} title={'Period '+(i+1)} />)}</div><div className="axis"><span>12 periods</span><b>Current: {cfg.stats[0][0]}</b></div></div><GlobalMap label={slug==='threat-intelligence'?'Threat activity':'Global security coverage'} /></div>
      </section>
      <section className="panel"><div className="panelhead"><div><span className="eyebrow">MODULE WORKSPACE</span><h2>Priority observations</h2></div><span className="pill">{cfg.rows.length} TRACKED</span></div><div className="table">{cfg.rows.map((r,i)=><div className="row" key={i}><div><strong>{r[0]}</strong><small>{r[3]}</small></div><span className={'severity '+(r[2].toLowerCase()==='critical'?'critical':r[2].toLowerCase()==='high'?'high':'medium')}>{r[2]}</span><span>{r[1]}</span></div>)}</div></section>
      <section className="lower"><div className="panel architecture"><span className="eyebrow">CONTROLLED WORKFLOW</span><h2>Security lifecycle</h2><div className="flow">{cfg.flow.map((x,i)=><span key={x}><b>{x}</b>{i<cfg.flow.length-1&&<i>→</i>}</span>)}</div><p>Module decisions remain tenant-scoped and feed the common CyberOS control plane for authorization, evidence, audit, risk and reporting.</p><button className="primary action" onClick={launch} disabled={running}>{running?'Processing…':'Run safe synthetic assessment →'}</button>{jobState&&<div className="status">{jobState}</div>}</div>
      <div className="panel"><span className="eyebrow">LIVE CONTROL PLANE</span><h2>Recent execution</h2><div className="table">{jobs.length?jobs.slice(0,4).map(j=><div className="row compact" key={j.id}><div><strong>{j.capability}</strong><small>{j.target}</small></div><span className="severity">{j.state}</span><span>{new Date(j.created_at).toLocaleTimeString()}</span></div>):<div className="empty">No jobs submitted yet.</div>}</div></div></section>
      <section className="panel"><span className="eyebrow">PLATFORM COVERAGE</span><h2>Global security context</h2><div className="context-grid"><Context label="Cloud" value="AWS · Azure · GCP" score="91%"/><Context label="On-premise" value="Data center · Network" score="76%"/><Context label="Hybrid" value="Identity · Connectivity" score="68%"/><Context label="Applications" value="Web · API · Mobile" score="84%"/></div></section>
      <footer>CYBEROS M2 · {cfg.name} workspace · Portal 3100 / API 8100 / PostgreSQL 5433</footer>
    </section></main>;
}
function Metric({n,l,s}){return <div className="metric"><strong>{n}</strong><span>{l}</span><small>{s}</small></div>}
function Context({label,value,score}){return <div className="context-card"><span>{label}</span><strong>{score}</strong><small>{value}</small><div className="progress"><i style={{width:score}} /></div></div>}
function GlobalMap({label}){const dots=[[16,38],[28,30],[36,58],[48,34],[57,46],[67,29],[76,53],[85,39],[91,61]];return <div className="map-card"><h3>{label}</h3><div className="world-map"><svg viewBox="0 0 600 270" role="img" aria-label="Global security analytics map"><path d="M42 94l48-31 66 12 25 38-37 34-56-8-39-22zm180-39l52-25 74 12 33 42-35 34-72-3-47-29zm199 30l58-20 62 31 18 48-48 29-64-12-34-38zM145 183l66-17 52 25-25 35-82-2z" fill="none" stroke="currentColor" strokeOpacity=".18" strokeWidth="2"/>{dots.map(([x,y],i)=><circle key={i} cx={x*6} cy={y*4.2} r={i%3===0?5:3} fill="currentColor" opacity={i%3===0?.9:.55}/>)}</svg></div><div className="map-legend"><span>● High activity</span><span>● Monitored</span><span>● Correlated</span></div></div>}
