import os
import json
from datetime import datetime, timezone
import psycopg
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

router=APIRouter(prefix="/api/v1/customer",tags=["Customer Assessment"])
DB=os.environ.get("DATABASE_URL","postgresql://cyberos:cyberos_dev_only@localhost:5433/cyberos")
class Request(BaseModel):
    tenant_id:str; asset_id:str; profile:str=Field(min_length=2,max_length=60); authorized:bool=False
CHECKS={
 "firewall":[("Management-plane exposure","high","Restrict administrative access and require strong authentication."),("Rulebase review","medium","Remove stale or overly broad rules and document business justification."),("Security logging","medium","Forward administrative and security events to centralized monitoring.")],
 "router":[("Management services","high","Disable unnecessary management services and restrict management sources."),("Routing control","medium","Protect routing adjacencies and validate route policy."),("Configuration backup","low","Maintain versioned, access-controlled configuration backups.")],
 "switch":[("Layer-2 protection","medium","Apply approved edge-port and control-plane protections."),("Unused ports","medium","Disable or quarantine unused ports and document exceptions."),("Management separation","high","Separate device administration from user traffic.")],
 "server":[("Patch posture","high","Apply approved security updates and verify remediation."),("Privileged access","high","Limit administrative access and review privileged groups."),("Host logging","medium","Collect security logs and verify retention and monitoring.")],
 "web_application":[("Security headers","medium","Apply the approved security-header baseline and retest."),("Authentication","high","Review session, MFA and account-recovery controls."),("Input validation","high","Use server-side validation and safe parameterized database access.")],
 "api":[("API authorization","high","Enforce object- and function-level authorization."),("Input validation","high","Constrain request data and use safe database access patterns."),("API logging","medium","Capture security-relevant API activity without secrets.")],
}
FRAMEWORKS={"pci-dss":["PCI DSS 4.0.1 Req. 2","PCI DSS 4.0.1 Req. 6","PCI DSS 4.0.1 Req. 7","PCI DSS 4.0.1 Req. 10"],"iso-27001":["ISO/IEC 27001:2022 A.5","ISO/IEC 27001:2022 A.8","Risk treatment evidence"],"nist-csf":["GV Govern","ID Identify","PR Protect","DE Detect","RS Respond","RC Recover"],"general-hardening":["Secure configuration","Least privilege","Logging/monitoring","Encryption"],"vulnerability":["Asset context","Exposure","Exploitability","Remediation priority","Verification"]}

def db():return psycopg.connect(DB,connect_timeout=3)
@router.post("/assessment/synthetic")
def synthetic(req:Request):
 if not req.authorized: raise HTTPException(status_code=403,detail="Explicit authorization acknowledgement is required")
 with db() as conn:
  with conn.cursor() as cur:
   cur.execute("SELECT id,name,asset_type,identifier,environment,criticality,exposure FROM assets WHERE id=%s AND tenant_id=%s",(req.asset_id,req.tenant_id)); asset=cur.fetchone()
   if not asset: raise HTTPException(status_code=404,detail="Asset is outside this tenant")
   cur.execute("SELECT id,name FROM tenants WHERE id=%s",(req.tenant_id,)); tenant=cur.fetchone()
   if not tenant: raise HTTPException(status_code=404,detail="Tenant not found")
   cur.execute("SELECT id FROM identities WHERE tenant_id=%s ORDER BY created_at LIMIT 1",(req.tenant_id,)); actor=cur.fetchone()
   checks=CHECKS.get(asset[2],CHECKS["server"]); weights={"critical":30,"high":20,"medium":10,"low":4}; score=max(0,100-sum(weights.get(s,5) for _,s,_ in checks)); now=datetime.now(timezone.utc); report_id=f"{str(req.tenant_id)[:8].upper()}-{now.strftime('%Y%m%d%H%M%S')}"
   findings=[{"title":t,"severity":s,"status":"review","evidence":"Synthetic evidence generated by CyberOS customer workspace","remediation":r} for t,s,r in checks]
   cur.execute("INSERT INTO jobs (tenant_id,requested_by,authorization_id,capability,target,state,parameters) SELECT %s,%s,id,'demo.finding_fixture',%s,'completed',%s FROM authorization_contexts WHERE tenant_id=%s AND status='active' ORDER BY created_at DESC LIMIT 1 RETURNING id",(req.tenant_id,actor[0] if actor else None,asset[3],json.dumps({"synthetic_assessment":True,"profile":req.profile,"report_id":report_id,"score":score}))); job=cur.fetchone()
   if job: cur.execute("INSERT INTO audit_events (tenant_id,actor_id,event_type,resource_type,resource_id,decision,metadata) VALUES (%s,%s,'customer.synthetic_assessment.completed','job',%s,'allow',%s)",(req.tenant_id,actor[0] if actor else None,job[0],json.dumps({"asset_id":req.asset_id,"profile":req.profile,"report_id":report_id})))
   conn.commit()
 return {"report_id":report_id,"generated_at":now.isoformat(),"tenant":tenant[1],"asset":{"id":str(asset[0]),"name":asset[1],"type":asset[2],"identifier":asset[3],"environment":asset[4],"criticality":asset[5],"exposure":asset[6]},"assessment":{"name":req.profile,"standards":FRAMEWORKS.get(req.profile,FRAMEWORKS['general-hardening'])},"score":score,"risk_rating":"high" if score<55 else "medium" if score<80 else "low","controls_reviewed":FRAMEWORKS.get(req.profile,FRAMEWORKS['general-hardening']),"findings":findings,"job_id":str(job[0]) if job else None,"disclaimer":"Synthetic customer-workspace report. No network traffic or exploitation was performed; use the approved customer agent for real authorized assessment execution."}
